language: node_js
node_js:
  - 6
  - 7
  - 8
  - 10
  - lts/*
  - node
before_script:
  - lerna bootstrap
  - ./test/prism.sh &
  - sleep 5
script:
  - yarn test:files
  - yarn test:license
  - yarn test:typescript
  - yarn test:mail
  - yarn test:client
  - yarn test:helpers
  - yarn lint
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - git reset HEAD --hard
deploy:
  - provider: script
    script: "lerna publish from-package --yes"
    skip_cleanup: true
    on:
      tags: true
      node: 10

notifications:
  slack:
    if: branch = master
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: i4B6L4/Wv1Z9jLSIH6UDa/rgARh472iCd44zLGYjHjXu7RRmDYrS4ZtE3vl5N/Xd8PVpBpAhsFXC8rG5zYEWCsU7UdRlKaHHz5CcLWFX25QP2PQaK5cKMR64mUgHi0lKQmt258HPrvPV1JqxF3nP+yJLWnB65QLMyEukCTK5N1c=
